BEGIN;

CREATE TABLE IF NOT EXISTS tipo_unidad (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_tipo character varying(100) NOT NULL,
    CONSTRAINT pk_tipo_unidad PRIMARY KEY (id),
    CONSTRAINT uq_tipo_unidad_nombre_tipo UNIQUE (nombre_tipo)
);

CREATE TABLE IF NOT EXISTS municipio (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_municipio character varying(100) NOT NULL,
    CONSTRAINT pk_municipio PRIMARY KEY (id),
    CONSTRAINT uq_municipio_nombre_municipio UNIQUE (nombre_municipio)
);

CREATE TABLE IF NOT EXISTS localidad (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_localidad character varying(150) NOT NULL,
    municipio_id integer NULL,
    CONSTRAINT pk_localidad PRIMARY KEY (id),
    CONSTRAINT uq_localidad_nombre_localidad_municipio_id UNIQUE (nombre_localidad, municipio_id),
    CONSTRAINT fk_localidad_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipio (id)
);

CREATE TABLE IF NOT EXISTS unidad_medica (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cluessa character varying(20) NULL,
    cluesimb character varying(20) NULL,
    nombre character varying(255) NOT NULL,
    direccion text NULL,
    latitud numeric(10,6) NULL,
    longitud numeric(10,6) NULL,
    estrato_unidad character varying(10) NULL,
    nivel_atencion character varying(30) NULL,
    tipo_unidad_id integer NULL,
    localidad_id integer NULL,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_unidad_medica PRIMARY KEY (id),
    CONSTRAINT fk_unidad_medica_tipo_unidad_id FOREIGN KEY (tipo_unidad_id) REFERENCES tipo_unidad (id),
    CONSTRAINT fk_unidad_medica_localidad_id FOREIGN KEY (localidad_id) REFERENCES localidad (id)
);

CREATE TABLE IF NOT EXISTS tipologia (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    es_segundo_nivel boolean NULL DEFAULT false,
    CONSTRAINT pk_tipologia PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tipologia_unidad (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    unidad_medica_id integer NOT NULL,
    tipologia_id integer NOT NULL,
    fuente text NULL,
    creado_en timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT pk_tipologia_unidad PRIMARY KEY (id),
    CONSTRAINT uq_tipologia_unidad UNIQUE (unidad_medica_id),
    CONSTRAINT fk_tipologia_unidad_unidad_medica_id FOREIGN KEY (unidad_medica_id) REFERENCES unidad_medica (id) ON DELETE CASCADE,
    CONSTRAINT fk_tipologia_unidad_tipologia_id FOREIGN KEY (tipologia_id) REFERENCES tipologia (id)
);

CREATE INDEX IF NOT EXISTS ix_localidad_municipio_id ON localidad (municipio_id);
CREATE INDEX IF NOT EXISTS ix_unidad_medica_tipo_unidad_id ON unidad_medica (tipo_unidad_id);
CREATE INDEX IF NOT EXISTS ix_unidad_medica_localidad_id ON unidad_medica (localidad_id);
CREATE INDEX IF NOT EXISTS ix_tipologia_unidad_tipologia_id ON tipologia_unidad (tipologia_id);

COMMIT;
