BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.persona (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_completo character varying(150) NOT NULL,
    cargo character varying(100) NULL,
    unidad_medica_id integer NULL,
    creado_en timestamp without time zone NULL DEFAULT now(),
    actualizado_en timestamp without time zone NULL DEFAULT now(),
    nombres character varying(150) NULL,
    apellidos character varying(150) NULL,
    rfc character varying(13) NULL,
    curp character varying(18) NULL,
    correo_principal text NULL,
    username character varying(100) NULL,
    activo boolean NOT NULL DEFAULT true,
    fecha_baja timestamp with time zone NULL,
    CONSTRAINT persona_pkey PRIMARY KEY (id),
    CONSTRAINT persona_unidad_medica_id_fkey
        FOREIGN KEY (unidad_medica_id) REFERENCES public.unidad_medica(id) ON DELETE SET NULL
);

ALTER TABLE public.persona
    ADD COLUMN IF NOT EXISTS user_id uuid NULL;

DO $$
BEGIN
    IF to_regclass('public."Users"') IS NULL THEN
        RAISE EXCEPTION 'La tabla public."Users" debe existir antes de asociar persona.user_id.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_persona_user'
          AND conrelid = 'public.persona'::regclass
    ) THEN
        ALTER TABLE public.persona
            ADD CONSTRAINT fk_persona_user
            FOREIGN KEY (user_id) REFERENCES public."Users"("Id") ON DELETE SET NULL;
    END IF;
END;
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_persona_user_id
    ON public.persona (user_id)
    WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_persona_correo_principal_ci
    ON public.persona (lower(correo_principal))
    WHERE correo_principal IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_persona_curp
    ON public.persona (curp)
    WHERE curp IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_persona_rfc
    ON public.persona (rfc)
    WHERE rfc IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_persona_username_ci
    ON public.persona (lower(username))
    WHERE username IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_persona_activo_unidad
    ON public.persona (activo, unidad_medica_id);

CREATE INDEX IF NOT EXISTS ix_persona_activo_nombre
    ON public.persona (activo, lower(nombre_completo));

CREATE INDEX IF NOT EXISTS idx_persona_nombre_trgm
    ON public.persona USING gin (nombre_completo gin_trgm_ops);

CREATE OR REPLACE FUNCTION public.set_nombre_completo()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.nombres IS NOT NULL OR NEW.apellidos IS NOT NULL THEN
        NEW.nombre_completo := btrim(coalesce(NEW.nombres, '') || ' ' || coalesce(NEW.apellidos, ''));
    END IF;

    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS t_persona_nombre ON public.persona;
CREATE TRIGGER t_persona_nombre
BEFORE INSERT OR UPDATE OF nombres, apellidos
ON public.persona
FOR EACH ROW
EXECUTE FUNCTION public.set_nombre_completo();

CREATE OR REPLACE FUNCTION public.set_persona_actualizado_en()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.actualizado_en := now();
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS t_persona_actualizado_en ON public.persona;
CREATE TRIGGER t_persona_actualizado_en
BEFORE UPDATE
ON public.persona
FOR EACH ROW
EXECUTE FUNCTION public.set_persona_actualizado_en();

-- persona es la fuente de verdad del correo. Se retira la sincronizacion
-- bidireccional con persona_correo; la tabla heredada se conserva por ahora
-- para poder auditar o migrar sus datos antes de eliminarla definitivamente.
DROP TRIGGER IF EXISTS t_persona_sync_to_persona_correo ON public.persona;
DO $$
BEGIN
    IF to_regclass('public.persona_correo') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS t_persona_correo_sync_to_persona ON public.persona_correo;
    END IF;
END;
$$;

DROP FUNCTION IF EXISTS public.f_sync_persona_correo_from_persona();
DROP FUNCTION IF EXISTS public.f_sync_persona_from_persona_correo();

COMMIT;
