using Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Persistence;

public static class DbInitializer
{
    public static async Task SeedAsync(AppDbContext dbContext, CancellationToken cancellationToken = default)
    {
        await EnsureSchemaAsync(dbContext, cancellationToken);

        if (await dbContext.Users.AnyAsync(cancellationToken))
        {
            await AssignDemoAdminRoleAsync(dbContext, cancellationToken);
            return;
        }

        var demoUser = new User
        {
            Email = "demo@example.com",
            PasswordHash = BCrypt.Net.BCrypt.HashPassword("Password123!", 12),
            CreatedAt = DateTime.UtcNow,
            IsActive = true
        };

        dbContext.Users.Add(demoUser);
        await dbContext.SaveChangesAsync(cancellationToken);
        await AssignDemoAdminRoleAsync(dbContext, cancellationToken);
    }

    private static async Task EnsureSchemaAsync(AppDbContext dbContext, CancellationToken cancellationToken)
    {
        await dbContext.Database.EnsureCreatedAsync(cancellationToken);

        await dbContext.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Users" (
                "Id" uuid NOT NULL,
                "Email" character varying(256) NOT NULL,
                "PasswordHash" character varying(256) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "IsActive" boolean NOT NULL,
                CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");

            CREATE TABLE IF NOT EXISTS "UserRefreshTokens" (
                "Id" uuid NOT NULL,
                "UserId" uuid NOT NULL,
                "Token" character varying(128) NOT NULL,
                "ExpiresUtc" timestamp with time zone NOT NULL,
                "IsRevoked" boolean NOT NULL,
                "CreatedDate" timestamp with time zone NOT NULL,
                "RevokedAtUtc" timestamp with time zone NULL,
                CONSTRAINT "PK_UserRefreshTokens" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_UserRefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserRefreshTokens_Token" ON "UserRefreshTokens" ("Token");
            CREATE INDEX IF NOT EXISTS "IX_UserRefreshTokens_UserId" ON "UserRefreshTokens" ("UserId");

            CREATE TABLE IF NOT EXISTS roles (
                code character varying(80) NOT NULL,
                descripcion character varying(200) NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                updated_at timestamp with time zone NULL,
                CONSTRAINT pk_roles PRIMARY KEY (code)
            );

            CREATE TABLE IF NOT EXISTS user_roles (
                user_id uuid NOT NULL,
                role_code character varying(80) NOT NULL,
                assigned_at timestamp with time zone NOT NULL DEFAULT now(),
                assigned_by_user_id uuid NULL,
                revoked_at timestamp with time zone NULL,
                is_active boolean NOT NULL DEFAULT true,
                CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_code),
                CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" ("Id") ON DELETE CASCADE,
                CONSTRAINT fk_user_roles_roles_role_code FOREIGN KEY (role_code) REFERENCES roles (code) ON DELETE RESTRICT,
                CONSTRAINT fk_user_roles_users_assigned_by_user_id FOREIGN KEY (assigned_by_user_id) REFERENCES "Users" ("Id") ON DELETE SET NULL
            );

            CREATE INDEX IF NOT EXISTS ix_user_roles_role_code ON user_roles (role_code);
            CREATE INDEX IF NOT EXISTS ix_user_roles_active_user_id ON user_roles (user_id) WHERE is_active = true;

            CREATE TABLE IF NOT EXISTS tipo_unidad (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                nombre_tipo character varying(100) NOT NULL,
                CONSTRAINT pk_tipo_unidad PRIMARY KEY (id),
                CONSTRAINT uq_tipo_unidad_nombre_tipo UNIQUE (nombre_tipo)
            );

            CREATE TABLE IF NOT EXISTS municipio (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                nombre_municipio character varying(100) NOT NULL,
                CONSTRAINT pk_municipio PRIMARY KEY (id),
                CONSTRAINT uq_municipio_nombre_municipio UNIQUE (nombre_municipio)
            );

            CREATE TABLE IF NOT EXISTS localidad (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                nombre_localidad character varying(150) NOT NULL,
                municipio_id integer NULL,
                CONSTRAINT pk_localidad PRIMARY KEY (id),
                CONSTRAINT uq_localidad_nombre_localidad_municipio_id UNIQUE (nombre_localidad, municipio_id),
                CONSTRAINT fk_localidad_municipio_id FOREIGN KEY (municipio_id) REFERENCES municipio (id)
            );

            CREATE TABLE IF NOT EXISTS unidad_medica (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                cluessa character varying(20) NULL,
                cluesimb character varying(20) NULL,
                nombre character varying(255) NOT NULL,
                direccion text NULL,
                latitud numeric(10,6) NULL,
                longitud numeric(10,6) NULL,
                estrato_unidad character varying(10) NULL,
                nivel_atencion character varying(30) NULL,
                tipo_unidad_id integer NULL,
                localidad_id integer NULL,
                activo boolean NOT NULL DEFAULT true,
                CONSTRAINT pk_unidad_medica PRIMARY KEY (id),
                CONSTRAINT fk_unidad_medica_tipo_unidad_id FOREIGN KEY (tipo_unidad_id) REFERENCES tipo_unidad (id),
                CONSTRAINT fk_unidad_medica_localidad_id FOREIGN KEY (localidad_id) REFERENCES localidad (id)
            );

            CREATE TABLE IF NOT EXISTS tipologia (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                nombre text NOT NULL,
                es_segundo_nivel boolean NULL DEFAULT false,
                CONSTRAINT pk_tipologia PRIMARY KEY (id)
            );

            CREATE TABLE IF NOT EXISTS tipologia_unidad (
                id integer GENERATED BY DEFAULT AS IDENTITY,
                unidad_medica_id integer NOT NULL,
                tipologia_id integer NOT NULL,
                fuente text NULL,
                creado_en timestamp with time zone NULL DEFAULT now(),
                CONSTRAINT pk_tipologia_unidad PRIMARY KEY (id),
                CONSTRAINT uq_tipologia_unidad UNIQUE (unidad_medica_id),
                CONSTRAINT fk_tipologia_unidad_unidad_medica_id FOREIGN KEY (unidad_medica_id) REFERENCES unidad_medica (id) ON DELETE CASCADE,
                CONSTRAINT fk_tipologia_unidad_tipologia_id FOREIGN KEY (tipologia_id) REFERENCES tipologia (id)
            );

            CREATE INDEX IF NOT EXISTS ix_localidad_municipio_id ON localidad (municipio_id);
            CREATE INDEX IF NOT EXISTS ix_unidad_medica_tipo_unidad_id ON unidad_medica (tipo_unidad_id);
            CREATE INDEX IF NOT EXISTS ix_unidad_medica_localidad_id ON unidad_medica (localidad_id);
            CREATE INDEX IF NOT EXISTS ix_tipologia_unidad_tipologia_id ON tipologia_unidad (tipologia_id);

            INSERT INTO roles (code, descripcion)
            VALUES
                ('ADMIN_TIC', 'Administrador TI'),
                ('FINANZAS', 'Operación finanzas'),
                ('ABASTO', 'Operación abasto'),
                ('JURIDICO', 'Operación juridico'),
                ('RECURSOS_HUMANOS', 'Operación Departamento de Personal'),
                ('RECURSOS_MATERIALES', 'Operación RM'),
                ('ATENCION_MEDICA', 'Operación Atencion Medica'),
                ('UNIDAD_MEDICA', 'Operación Unidad Medica'),
                ('PLANEACION_ESTRATEGICA', 'Operación Planeacion Estrategica'),
                ('ACCION_COMUNITARIA', 'Operación Accion Comunitaria'),
                ('CONSERVACION', 'Operación Conservacion y Mantenimiento'),
                ('SUPERVISION_REGIONAL', 'Operación Supervision Regional'),
                ('SUPERVISION_SALUD', 'Operación Supervision en Salud'),
                ('EPIDEMIOLOGIA', 'Operación Epidemiologia'),
                ('ENFERMERIA', 'Operación Enfermería'),
                ('CONDUCCION', 'Operación Conducción'),
                ('JURISDICCION', 'Operación Jurisdicción'),
                ('COORDINACION', 'Coordinación Estatal'),
                ('PROGRAMAS_PREVENTIVOS', 'Operación Programas Preventivos'),
                ('EDUCACION_INVESTIGACION', 'Operación Educación e investigación'),
                ('SOLICITUDES_ABASTO', 'Captura de solicitudes para abasto (piloto)')
            ON CONFLICT (code) DO UPDATE
            SET descripcion = EXCLUDED.descripcion,
                is_active = true,
                updated_at = now();
            """, cancellationToken);
    }

    private static Task AssignDemoAdminRoleAsync(AppDbContext dbContext, CancellationToken cancellationToken)
    {
        return dbContext.Database.ExecuteSqlRawAsync("""
            INSERT INTO user_roles (user_id, role_code)
            SELECT users."Id", 'ADMIN_TIC'
            FROM "Users" users
            WHERE lower(users."Email") = lower('demo@example.com')
            ON CONFLICT (user_id, role_code) DO UPDATE
            SET is_active = true,
                revoked_at = NULL,
                assigned_at = now();
            """, cancellationToken);
    }

    private static async Task<bool> TableExistsAsync(
        AppDbContext dbContext,
        string tableName,
        CancellationToken cancellationToken)
    {
        var connection = dbContext.Database.GetDbConnection();
        var shouldClose = connection.State == System.Data.ConnectionState.Closed;

        if (shouldClose)
        {
            await connection.OpenAsync(cancellationToken);
        }

        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText = """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name = @tableName
                );
                """;

            var parameter = command.CreateParameter();
            parameter.ParameterName = "tableName";
            parameter.Value = tableName;
            command.Parameters.Add(parameter);

            var result = await command.ExecuteScalarAsync(cancellationToken);
            return result is true;
        }
        finally
        {
            if (shouldClose)
            {
                await connection.CloseAsync();
            }
        }
    }
}
